project:
  type: book

book:
  title: "Berland-Wildhay Watershed Connectivity Remediation Planning"
  author: "Canadian Wildlife Federation"
  date: "6/30/2023"
  chapters:
    - index.qmd
    - part: "Model Purpose and Approach"
      chapters:
        - intro.qmd
        - model-overview.qmd
    - part: "Software Documentation"
      chapters:
        - software-docs.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



