# Requirements and Configuration

## Software Requirements

- Python (tested with version 3.9.5)
  + Modules: shapely, psycopg2, tifffile, requests
- GDAL/ORG (comes installed with QGIS or can install standalone)
- PostgreSQL/PostGIS database

## Configuration

All configuration is setup in the ``config.ini`` file. Before running any scripts you should ensure the information in this file is correct.

All of the scripts allow for a custom configuration file to be specified by providing it as the ``-c`` argument to the program. If not supplied, the default ``config.ini`` file will be used. For example:

``prompt> create_db.py -c custom_config.ini``

The ```config.ini``` and ```appconfig.py``` files are included in the ```/src``` and ```/src/processing scripts``` folders by default. If you want to run a script from another folder (e.g., ```src/load_alberta```), you will need to make sure the ```config.ini``` and ```appconfig.py``` files are in that folder as well.

We recommend editing a single ```config.ini``` file with the configuration parameters you need, then copying this file to the other folders if you want to run individual scripts.

### Configuration File Definitions {.unnumbered}

```
[OGR]
ogr = location of ogr2ogr executable
gdalinfo = location of gdalinfo executable
gdalsrsinfo = location of gdalsrsinfo executable
proj = optional location of proj library

[DATABASE]
host = database host
port = database post
name = database name

data_schema = name of main schema for holding raw stream data
stream_table = names of streams table
fish_species_table = name of fish species table
working_srid = the srid (3400) of the stream data - these scripts use the function st_length to compute stream length so the raw data should be in a meters based projection (or reprojected before used)

aquatic_habitat_table = table name for fish aquatic habitat data
fish_stocking_table = table name for fish stocking data
fish_survey_table = table name for fish survey data

[CABD_DATABASE] buffer = this is the buffer distance to grab features - the units are in the working_srid so if its meters 200 is reasonable, if it's degrees something like 0.001 is reasonable
snap_distance = distance (in working srid units) for snapping point features #to the stream network (fish observation data, barrier data etc)

[CREATE_LOAD_SCRIPT]
raw_data = raw alberta data
road_table = road table name
rail_table = rail table name
trail_table = trail table name

[PROCESSING]
stream_table = stream table name

[WATERSHEDID 1] -> there will be one section for each watershed with a unique section name
watershed_id = watershed id to process nhn_watershed_id = nhn watershed id to process output_schema = output schema name
fish_observation_data = zip file containing fish observation data
assessment_data = spatial file containing assessment data

[WATERSHEDID 2] -> there will be one section for each watershed with a unique section name
watershed_id = watershed id to process nhn_watershed_id = nhn watershed id to process output_schema = output schema name
fish_observation_data = zip file containing fish observation data assessment_data = spatial file containing assessment data

[ELEVATION_PROCESSING]
dem_directory = directory containing dem
3dgeometry_field = field name (in streams table) for geometry that stores raw elevation data
smoothedgeometry_field = field name (in streams table) for geometry that stores smoothed elevation data

[MAINSTEM_PROCESSING]
mainstem_id = name of mainstem id field (in streams table)
downstream_route_measure = name of downstream route measure field
upstream_route_measure =name upstream route measure field

[GRADIENT_PROCESSING]
vertex_gradient_table = table for storing vertex gradient values
segment_gradient_field = name of segment gradient field (in streams table)
max_downstream_gradient_field = name of field for storing the maximum downstream segment gradient (in streams table)

[BARRIER_PROCESSING]
barrier_table = table for storing barriers gradient_barrier_table = table where gradient barriers are stored (type = gradient_barrier)

[CROSSINGS]
modelled_crossings_table = table for storing modelled crossings assessed_crossings_table = table for storing assessed crossings crossings_table = table for storing all stream crossings (both modelled and assessed)

join_distance = distance (in working srid units) for joining assessment data with modelled crossings

strahler_order_barrier_limit = all crossings on streams with Strahler order less than this will be considered barriers and treated similar to dams/waterfalls for habitat modelling

[HABITAT_STATS] stats_table = this table will be created in the [DATABASE].data_schema schema and contain watershed statistics

watershed_data_schemas = the list of processing schemas to include in the stats table; the schemas must exist and data must be fully processed
```